/*
 * Agent Platform
 *
 * This is a specification for openapi using
 *
 * API version: 1.0.0
 * Contact: agentPlatform@grs.uh.cu
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package lib_agent
// Error struct for Error
type Error struct {
	Code int32 `json:"code"`
	Message string `json:"message"`
}
