/*
 * Agent Platform
 *
 * This is a specification for openapi using
 *
 * API version: 1.0.0
 * Contact: agentPlatform@grs.uh.cu
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package lib_agent
// Agent struct for Agent
type Agent struct {
	Name string `json:"Name,omitempty"`
	Function string `json:"Function,omitempty"`
	EndpointService []Addr `json:"EndpointService,omitempty"`
	IsAliveService map[string]Addr `json:"IsAliveService,omitempty"`
	Documentation map[string]Addr `json:"Documentation,omitempty"`
	TestCases []TestCase `json:"TestCases,omitempty"`
}
