/*
 * Agent Platform
 *
 * This is a specification for openapi using
 *
 * API version: 1.0.0
 * Contact: agentPlatform@grs.uh.cu
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package lib_agent
// TestCase struct for TestCase
type TestCase struct {
	Input string `json:"Input"`
	Output string `json:"Output"`
}
