/*
 * Agent Platform
 *
 * This is a specification for openapi using
 *
 * API version: 1.0.0
 * Contact: agentPlatform@grs.uh.cu
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package lib_agent
// Addr struct for Addr
type Addr struct {
	Ip string `json:"Ip"`
	Port int64 `json:"Port"`
}
